CREATE TABLE race (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    skills VARCHAR(100) NOT NULL,
    abilities VARCHAR(600) NOT NULL,

    PRIMARY KEY(id)
);